### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alvaroartano**
Atatonic link didn't work, so I deleted it.

### CODE REVIEW

**Comment by neiesc** [comment]
@alvaroartano  Maybe will be better remove ou link https://github.com/mavarick/atatonic-css-framwork https://github.com/kombat003/atatonic-css-framwork what do you think?

**Comment by neiesc** [comment]
Please open in main branch

**Comment by Jogai** [comment]
I think @timbenniks abandoned it. Otherwise it would be in his github.

**Comment by timbenniks** [comment]
> I think @timbenniks abandoned it. Otherwise it would be in his github.

True! I built this many years ago. It could still work but it's quite dated. Would you be interested if I did an update? I'd love to do that if there is interest.

**Comment by Jogai** [comment]
If you make it work with Vue 3 you might get some traction now. The bigger ones are still catching up

**Comment by timbenniks** [comment]
@Jogai Atatonic was, at the time, a pure CSS based framework that focused on simple layout but mainly on great typography. To make it more relevant maybe I should make it an extension to Tailwind? Or should I make it standalone? What do you all think?

**Comment by alvaroartano** [comment]
An extension to Tailwind would be sooooo good 👍

**Pull request closed without merging**
